#
# Available repositories are listed here:
# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#

sudo: false

language: cpp

install:
    - gem install coveralls-lcov

matrix:
    include:
        - env: COMPILER_VERSION=4.8
          os: linux
          compiler: g++
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-4.8
                      - libcppunit-dev

        - env: COMPILER_VERSION=4.9
          os: linux
          compiler: g++
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-4.9
                      - libcppunit-dev

        - env: COMPILER_VERSION=3.5
          os: linux
          compiler: clang++
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-3.5
                  packages:
                      - llvm-3.5
                      - clang-3.5
                      - libcppunit-dev

        - env: COMPILER_VERSION=3.6
          os: linux
          compiler: clang++
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-3.6
                  packages:
                      - llvm-3.6
                      - clang-3.6
                      - libcppunit-dev

        - env: COMPILER_VERSION=3.7
          os: linux
          compiler: clang++
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-3.7
                  packages:
                      - llvm-3.7
                      - clang-3.7
                      - libcppunit-dev

before_script:
    - mkdir build
    - cd build
    - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.12.orig.tar.gz
    - tar xfvz lcov_1.12.orig.tar.gz
    - make -C lcov-1.12
    - echo "Using compilers $CXX-${COMPILER_VERSION} and $CC-${COMPILER_VERSION}"
    - cmake -DCMAKE_CXX_COMPILER=$CXX-${COMPILER_VERSION} -DCMAKE_C_COMPILER=$CC-${COMPILER_VERSION} -DWITH_TESTS=1 ..


script:
    - make
    - make test

after_success:
    - make coverage
    - coveralls-lcov cov.info

